name: NuclearMusic
main: com.fcmcpe.nuclear.music.NuclearMusicPlugin
version: "${pom.version}"
api: ["1.0.9"]
author: EaseCation, PetteriM1
load: POSTWORLD
permissions:
  nuclearmusic.setup:
    default: op
